version: '3.9'
services:
  app:
    build:
      context: .
      args:
        - TZ=${TZ}
        - DATABASE_MONGODB_ENDPOINT=${DATABASE_MONGODB_ENDPOINT}
        - AUTH_JWT_SECRET=${AUTH_JWT_SECRET}
        - TWITTER_BEARER=${TWITTER_BEARER}
        - APTOS_PRIVATE_KEY=${APTOS_PRIVATE_KEY}
        - TELEGRAM_CLIENT_API_KEY=${TELEGRAM_CLIENT_API_KEY}
        - TELEGRAM_CLIENT_API_HASH=${TELEGRAM_CLIENT_API_HASH}
        - TELEGRAM_CLIENT_SESSION=${TELEGRAM_CLIENT_SESSION}
        - TELEGRAM_CLIENT_PHONE_NUMBER=${TELEGRAM_CLIENT_PHONE_NUMBER}
        - TELEGRAM_CLIENT_PHONE_CODE=${TELEGRAM_CLIENT_PHONE_CODE}
        - TELEGRAM_CLIENT_CONNECTION_RETRY_COUNT=${TELEGRAM_CLIENT_CONNECTION_RETRY_COUNT}
        - ELASTICSEARCH_ENDPOINT=${ELASTICSEARCH_ENDPOINT}
        - ELASTICSEARCH_AUTH_USERNAME=${ELASTICSEARCH_AUTH_USERNAME}
        - ELASTICSEARCH_AUTH_PASSWORD=${ELASTICSEARCH_AUTH_PASSWORD}
        - ELASTICSEARCH_LOG_INDEX=${ELASTICSEARCH_LOG_INDEX}
      dockerfile: ./docker/Dockerfile.${DOCKER_ENV}
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
