import { registerEnumType } from '@nestjs/graphql';

export enum QuestPolicyType {
  QUIZ = 'QUIZ',
  VERIFY_TWITTER_FOLLOW = 'VERIFY_TWITTER_FOLLOW',
  VERIFY_TWITTER_RETWEET = 'VERIFY_TWITTER_RETWEET',
  VERIFY_TWITTER_LIKING = 'VERIFY_TWITTER_LIKING',
  VERIFY_DISCORD = 'VERIFY_DISCORD',
  VERIFY_APTOS_BRIDGE_TO_APTOS = 'VERIFY_APTOS_BRIDGE_TO_APTOS',
  VERIFY_APTOS_HAS_NFT = 'VERIFY_APTOS_HAS_NFT',
  VERIFY_APTOS_EXIST_TX = 'VERIFY_APTOS_EXIST_TX',
  VERIFY_APTOS_HAS_ANS = 'VERIFY_APTOS_HAS_ANS',
}

registerEnumType(QuestPolicyType, { name: 'QuestPolicyType' });
