database:
  mongodb:
    endpoint: ${{ secrets.BETA_DATABASE_MONGODB_ENDPOINT }}
auth:
  jwt:
    secret: ${{ secrets.BETA_AUTH_JWT_SECRET }}
twitter:
  bearer: ${{ secrets.BETA_TWITTER_BEARER }}
aptos:
  privateKey: ${{ secrets.BETA_APTOS_PRIVATE_KEY }}
  nodeUrl: "https://fullnode.testnet.aptoslabs.com"
  faucetUrl: "https://faucet.testnet.aptoslabs.com"
