database:
  mongodb:
    endpoint: mongodb+srv://despread:tz33NSLcyu3ncFin@sakura-dev.rnnfkhn.mongodb.net/?retryWrites=true&w=majority
auth:
  jwt:
    secret: secret_key
twitter:
  bearer: AAAAAAAAAAAAAAAAAAAAAFsalgEAAAAAwaDGZtcFzWEfk42a%2Fx3ASEuaqNA%3DGFhDiKeG7QM4N1HmeWincFGW0ueie0TZVVVVJq8lag2EsQSj8a