database:
  mongodb:
    endpoint: mongodb+srv://despread:tz33NSLcyu3ncFin@sakura-dev.rnnfkhn.mongodb.net/?retryWrites=true&w=majority
auth:
  jwt:
    secret: secret_key
twitter:
  bearer: AAAAAAAAAAAAAAAAAAAAAFsalgEAAAAAwaDGZtcFzWEfk42a%2Fx3ASEuaqNA%3DGFhDiKeG7QM4N1HmeWincFGW0ueie0TZVVVVJq8lag2EsQSj8a
aptos:
  privateKey: "0xb95914417838f2feb1d64413aaa2ead275f851c5896a2ba7e2da8ae1e797942d"
  nodeUrl: "https://fullnode.testnet.aptoslabs.com"
  faucetUrl: "https://faucet.testnet.aptoslabs.com"
