database:
  mongodb:
    endpoint: mongodb+srv://despread:tz33NSLcyu3ncFin@sakura-dev.rnnfkhn.mongodb.net/?retryWrites=true&w=majority
auth:
  jwt:
    secret: secret_key
twitter:
  bearer: AAAAAAAAAAAAAAAAAAAAAE0algEAAAAAKfqol3JJRm84hTMYfn%2BtXrF15zg%3DJN3Pil9wFIedlifI5HApJt3Z5yPBBc4VQ3rEQqXLQsaeovdr0R