stacks-tracker-bot:
  telegram:
    api: 5326582412:AAE6c3muQoOlipHOYJgtveRPSTiIRJ9yjao
    options: {
      parse_mode: 'Markdown',
      reply_markup: {
        keyboard: [
          [ 'Get monitoring list' ],
          [ 'Add wallet', 'Delete wallet' ],
          [ 'Add tx notification', 'Delete tx notification' ],
          [ 'Add block notification', 'Delete block notification' ]
        ]
      }
    }
telegram-stat-bot:
  telegram:
    api: 5380146542:AAG7443maxpem0RDnx5MlTNOovv5zlh75Bc
    options: {
      parse_mode: 'Markdown'
    }
global-community-message-stat-bot:
  telegram:
    api: 5324465187:AAGGAvuS0gPDdAaeei6rekMCjuCvdbu4H-Y
    options: {
      parse_mode: 'Markdown'
    }
stacks:
  baseUrl: https://stacks-node-api.mainnet.stacks.co
elasticsearch:
  node: https://leo-e32fa2.es.us-central1.gcp.cloud.es.io:9243
  username: elastic
  password: zgA8MORyV98xpKEoMsM8DJwI
  indices:
    messageIndex: local-telegram-message
    chatStatusIndex: local-telegram-chat-status
    channelStatusIndex: local-telegram-channel-status
    stacksTrackerBotIndex: local-stacks-tracker-bot
    fearAndGreedIndex: local-fear-and-greed
    cryptoPriceIndex: local-crypto-price
    onChainDataInfoIndex: local-on-chain-data-info
    managementContentIndex: local-management-content
    errorLogIndex: local-error-log
database:
  name: despread-dev
  host: despread-rds.cpyzyqczrhaj.us-east-1.rds.amazonaws.com
  port: 3306
  username: admin
  password: WK39dEaHTy2Jcz8
  synchronize: false
telegram-client:
  apiKey: 9335628
  apiHash: 61b989181546a2b69befca1998f97985
  session: 1BQANOTEuMTA4LjU2LjEwMQG7Ws/zusM6RDJfUCG9bD+WC9iHKyLg/F8WGlStzTLg77mq334dotfn1opIIjzZyUenPFHdOES7nSeZsp0Ubbt7sA9iT6XzSUlaAvZiRlkiuQu12f4DUfFWiS/4B3aHDK5EceQVirMjaKRmiJJ2YppBVPXI/lBt4ahycQfS+bGY4j13EZau1PAVaHly21mPVMNCAK+H7bQTNW6O9Dz1PDtgtMX2sel0RWZ4To2m87NymOJsFNIJWeBTvk85iVBHogc82LxhTkFATuU6ykkQhfLToFz6FNmf+b5a8fvEialfTNn7i75LQW5JGvsu74rNXRARay6Q82SHRi8igHRskC8Nqg==
  phoneNumber: +821064836404
  phoneCode: 10561
  connectionRetryCount: 30