name: Docker Image CI

on:
  push:
    branches: [ develop ]

env:
  VERSION: ${{ github.sha }}
  DOCKER_IMAGE_NAME: 3ridge-backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push register app
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./Dockerfile.dev
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
